package com.strumenta.financialcalc.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BooleanType = 0;
  public static final int FinancialCalcSheet = 1;
  public static final int Input = 2;
  public static final int StringType = 3;
  public static final int Type = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xa50bd8d842c14879L, 0x98505fb2cea64ad0L);
    builder.put(0x28a7a476f630fde9L, BooleanType);
    builder.put(0x4801ddb81016ebcL, FinancialCalcSheet);
    builder.put(0x4801ddb81016ebfL, Input);
    builder.put(0x4801ddb81016ec5L, StringType);
    builder.put(0x4801ddb81016ec4L, Type);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
