package com.strumenta.businessorg.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Executor = 0;
  public static final int Organization = 1;
  public static final int Person = 2;
  public static final int Process = 3;
  public static final int ProcessStep = 4;
  public static final int Role = 5;
  public static final int RolePlayed = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L);
    builder.put(0x4923b41015896544L, Executor);
    builder.put(0x4923b41015868b94L, Organization);
    builder.put(0x4923b41015868b9aL, Person);
    builder.put(0x4923b41015868b9fL, Process);
    builder.put(0x4923b41015868bf0L, ProcessStep);
    builder.put(0x4923b41015868b97L, Role);
    builder.put(0x4923b41015880f85L, RolePlayed);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
