package com.strumenta.mpsserver.logic;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/*package*/ class NodeUtils {
  /*package*/ static String defaultLabel(SNode node) {
    return node.getName();
  }

}
