package com.strumenta.mpsserver.logic;

/*Generated by MPS */

import jetbrains.mps.references.Reference;

public class NotFoundException extends RuntimeException {
  private String myDescription;
  public String getDescription() {
    return this.myDescription;
  }
  private void _setDescription(String value) {
    this.myDescription = value;
  }
  private String setDescription(String value) {
    _setDescription(value);
    return value;
  }
  private Reference<String> refToDescription() {
    return new Reference<String>() {
      public String get() {
        return getDescription();
      }
      public void set(String value) {
        _setDescription(value);
      }
    };
  }
  public NotFoundException(String description) {
    super("element not found, " + description);
    this.setDescription(description);
  }
  public NotFoundException() {
    super("element not found");
    this.setDescription("<no description>");
  }
  @Override
  public String toString() {
    return "Not found - " + this.getDescription();
  }
}
