package com.strumenta.mpsserver.logic;

/*Generated by MPS */

import spark.Request;
import java.util.Objects;

public abstract class Routes {
  protected boolean queryFlag(Request req, String name, boolean defaultValue) {
    String stringValue = req.queryParams(name);
    if (stringValue == null) {
      return defaultValue;
    }
    if (Objects.equals(stringValue.toLowerCase(), "true")) {
      return true;
    }
    return false;
  }
  protected boolean queryFlag(Request req, String name) {
    return queryFlag(req, name, false);
  }
}
