package com.strumenta.businessorg.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Organization_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Person_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Process_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ProcessStep_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Role_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new RolePlayed_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new RolePlayed_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b94L), MetaIdFactory.conceptId(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b9aL), MetaIdFactory.conceptId(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b9fL), MetaIdFactory.conceptId(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868bf0L), MetaIdFactory.conceptId(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b97L), MetaIdFactory.conceptId(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015880f85L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015880f85L)).seal();
}
