package com.strumenta.businessorg.intentions;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public class MyInvocationRegister {

  public static class Invocation {
    public String intention;
    public SNode node;
    public EditorContext editorContext;
    public Invocation(String intention, SNode node, EditorContext editorContext) {
      this.intention = intention;
      this.node = node;
      this.editorContext = editorContext;
    }
  }

  private static List<Invocation> invocations = ListSequence.fromList(new LinkedList<Invocation>());

  public static void clear() {
    ListSequence.fromList(invocations).clear();
  }

  public static void register(String intention, SNode node, EditorContext editorContext) {
    ListSequence.fromList(invocations).addElement(new Invocation(intention, node, editorContext));
  }

  public static List<Invocation> getInvocations() {
    return invocations;
  }

}
