package com.strumenta.financialcalc.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FinancialCalcSheet_Constraints extends BaseConstraintsDescriptor {
  public FinancialCalcSheet_Constraints() {
    super(CONCEPTS.FinancialCalcSheet$Ux);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FinancialCalcSheet$Ux = MetaAdapterFactory.getConcept(0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ebcL, "com.strumenta.financialcalc.structure.FinancialCalcSheet");
  }
}
