package com.strumenta.mpsserver.logic;

/*Generated by MPS */

import spark.ResponseTransformer;

public class JsonTransformer implements ResponseTransformer {
  @Override
  public String render(Object model) {
    try {
      return Serialization.getInstance().jsonify(model);
    } catch (Throwable t) {
      t.printStackTrace();
      return "<SERIALIZATION ISSUE FOR  " + model + ">";
    }
  }
}
