package com.strumenta.mpsserver.logic;

/*Generated by MPS */

import com.strumenta.mpsprotocol.Message;
import com.strumenta.mpsprotocol.RequestForPropertyChange;
import com.strumenta.mpsprotocol.data.RegularNodeIDInfo;
import org.jetbrains.mps.openapi.util.Consumer;
import org.jetbrains.annotations.NotNull;

public class MessagesExecutor {

  private ServerController serverController;

  public MessagesExecutor(ServerController serverController) {
    this.serverController = serverController;
  }

  public void executeMessage(Message message) {
    if (message instanceof RequestForPropertyChange) {
      RequestForPropertyChange msg = ((RequestForPropertyChange) message);
      serverController.executePropertyChange(msg.getNode().getModel(), ((RegularNodeIDInfo) msg.getNode().getId()).getRegularId(), msg.getPropertyName(), msg.getPropertyValue(), new Consumer<Object>() {
        @Override
        public void consume(@NotNull Object p0) {
        }
      });
    }
  }
}
