package com.strumenta.financialcalc.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBooleanType = createDescriptorForBooleanType();
  /*package*/ final ConceptDescriptor myConceptFinancialCalcSheet = createDescriptorForFinancialCalcSheet();
  /*package*/ final ConceptDescriptor myConceptInput = createDescriptorForInput();
  /*package*/ final ConceptDescriptor myConceptStringType = createDescriptorForStringType();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBooleanType, myConceptFinancialCalcSheet, myConceptInput, myConceptStringType, myConceptType);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BooleanType:
        return myConceptBooleanType;
      case LanguageConceptSwitch.FinancialCalcSheet:
        return myConceptFinancialCalcSheet;
      case LanguageConceptSwitch.Input:
        return myConceptInput;
      case LanguageConceptSwitch.StringType:
        return myConceptStringType;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBooleanType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.financialcalc", "BooleanType", 0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x28a7a476f630fde9L);
    b.class_(false, false, false);
    b.super_("com.strumenta.financialcalc.structure.Type", 0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ec4L);
    b.origin("r:5a0d657d-9920-4de3-ab81-685de32279fd(com.strumenta.financialcalc.structure)/2929490913471299049");
    b.version(2);
    b.alias("boolean");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFinancialCalcSheet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.financialcalc", "FinancialCalcSheet", 0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ebcL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5a0d657d-9920-4de3-ab81-685de32279fd(com.strumenta.financialcalc.structure)/324292001770073788");
    b.version(2);
    b.aggregate("inputs", 0x4801ddb81017413L).target(0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ebfL).optional(true).ordered(true).multiple(true).origin("324292001770075155").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInput() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.financialcalc", "Input", 0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ebfL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5a0d657d-9920-4de3-ab81-685de32279fd(com.strumenta.financialcalc.structure)/324292001770073791");
    b.version(2);
    b.aggregate("type", 0x4801ddb81016ec2L).target(0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ec4L).optional(false).ordered(true).multiple(false).origin("324292001770073794").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStringType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.financialcalc", "StringType", 0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ec5L);
    b.class_(false, false, false);
    b.super_("com.strumenta.financialcalc.structure.Type", 0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ec4L);
    b.origin("r:5a0d657d-9920-4de3-ab81-685de32279fd(com.strumenta.financialcalc.structure)/324292001770073797");
    b.version(2);
    b.alias("string");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.financialcalc", "Type", 0xa50bd8d842c14879L, 0x98505fb2cea64ad0L, 0x4801ddb81016ec4L);
    b.class_(false, true, false);
    b.origin("r:5a0d657d-9920-4de3-ab81-685de32279fd(com.strumenta.financialcalc.structure)/324292001770073796");
    b.version(2);
    return b.create();
  }
}
