package com.strumenta.mpsserver.extensionkit.code;

/*Generated by MPS */


public interface MPSServerExtension {
  default String name() {
    return this.getClass().getCanonicalName();
  }
  /**
   * This method is not intended to be called directly
   * 
   * @param server 
   */
  void activate(ExtendableServer server);
}
