package com.strumenta.mpsserver.modelhierarchy;

/*Generated by MPS */

import org.jetbrains.mps.openapi.persistence.DataSource;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.persistence.DataSourceListener;

public class MyDataSource implements DataSource {
  @NotNull
  @Override
  public String getLocation() {
    throw new UnsupportedOperationException();
  }
  @Override
  public void addListener(@NotNull DataSourceListener listener) {
    throw new UnsupportedOperationException();
  }
  @Override
  public void removeListener(@NotNull DataSourceListener listener) {
    throw new UnsupportedOperationException();
  }
  @Override
  public long getTimestamp() {
    throw new UnsupportedOperationException();
  }
  @Override
  public boolean isReadOnly() {
    throw new UnsupportedOperationException();
  }
}
