package com.strumenta.businessorg.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptExecutor = createDescriptorForExecutor();
  /*package*/ final ConceptDescriptor myConceptOrganization = createDescriptorForOrganization();
  /*package*/ final ConceptDescriptor myConceptPerson = createDescriptorForPerson();
  /*package*/ final ConceptDescriptor myConceptProcess = createDescriptorForProcess();
  /*package*/ final ConceptDescriptor myConceptProcessStep = createDescriptorForProcessStep();
  /*package*/ final ConceptDescriptor myConceptRole = createDescriptorForRole();
  /*package*/ final ConceptDescriptor myConceptRolePlayed = createDescriptorForRolePlayed();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptExecutor, myConceptOrganization, myConceptPerson, myConceptProcess, myConceptProcessStep, myConceptRole, myConceptRolePlayed);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Executor:
        return myConceptExecutor;
      case LanguageConceptSwitch.Organization:
        return myConceptOrganization;
      case LanguageConceptSwitch.Person:
        return myConceptPerson;
      case LanguageConceptSwitch.Process:
        return myConceptProcess;
      case LanguageConceptSwitch.ProcessStep:
        return myConceptProcessStep;
      case LanguageConceptSwitch.Role:
        return myConceptRole;
      case LanguageConceptSwitch.RolePlayed:
        return myConceptRolePlayed;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForExecutor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.businessorg", "Executor", 0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015896544L);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7b9b5e1d-3054-41f7-a62a-e0116b0952e3(com.strumenta.businessorg.structure)/5270253970127414596");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOrganization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.businessorg", "Organization", 0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b94L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7b9b5e1d-3054-41f7-a62a-e0116b0952e3(com.strumenta.businessorg.structure)/5270253970127227796");
    b.version(2);
    b.property("multiple", 0x4923b41015868b9dL).type(PrimitiveTypeId.BOOLEAN).origin("5270253970127227805").done();
    b.aggregate("roles", 0x4923b4101587dca7L).target(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b97L).optional(true).ordered(true).multiple(true).origin("5270253970127314087").done();
    b.aggregate("persons", 0x4923b4101587dca5L).target(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b9aL).optional(true).ordered(true).multiple(true).origin("5270253970127314085").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPerson() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.businessorg", "Person", 0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b9aL);
    b.class_(false, false, false);
    b.parent(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015896544L);
    b.origin("r:7b9b5e1d-3054-41f7-a62a-e0116b0952e3(com.strumenta.businessorg.structure)/5270253970127227802");
    b.version(2);
    b.aggregate("roles", 0x4923b41015880fafL).target(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015880f85L).optional(true).ordered(true).multiple(true).origin("5270253970127327151").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcess() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.businessorg", "Process", 0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b9fL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7b9b5e1d-3054-41f7-a62a-e0116b0952e3(com.strumenta.businessorg.structure)/5270253970127227807");
    b.version(2);
    b.associate("organization", 0x4923b41015868ba2L).target(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b94L).optional(true).origin("5270253970127227810").done();
    b.aggregate("steps", 0x4923b41015868bf3L).target(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868bf0L).optional(true).ordered(true).multiple(true).origin("5270253970127227891").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcessStep() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.businessorg", "ProcessStep", 0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868bf0L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7b9b5e1d-3054-41f7-a62a-e0116b0952e3(com.strumenta.businessorg.structure)/5270253970127227888");
    b.version(2);
    b.associate("executor", 0x4923b4101589654dL).target(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015896544L).optional(true).origin("5270253970127414605").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRole() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.businessorg", "Role", 0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b97L);
    b.class_(false, false, false);
    b.parent(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015896544L);
    b.origin("r:7b9b5e1d-3054-41f7-a62a-e0116b0952e3(com.strumenta.businessorg.structure)/5270253970127227799");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRolePlayed() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.strumenta.businessorg", "RolePlayed", 0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015880f85L);
    b.class_(false, false, false);
    b.origin("r:7b9b5e1d-3054-41f7-a62a-e0116b0952e3(com.strumenta.businessorg.structure)/5270253970127327109");
    b.version(2);
    b.associate("role", 0x4923b41015880f86L).target(0x96ad5b8f04fe4e16L, 0xa7d60e014b8726e4L, 0x4923b41015868b97L).optional(false).origin("5270253970127327110").done();
    return b.create();
  }
}
