package com.strumenta.mpsserver.extensionkit.code;

/*Generated by MPS */


public interface ExtendableServer {
  void registerConceptSpecificAction(String conceptName, String actionName, Action action);
}
