package com.strumenta.mpsserver.ide.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ProjectPluginPart;
import jetbrains.mps.project.MPSProject;

public class MPSServerIDEProject_ProjectPluginPart extends ProjectPluginPart {
  public MPSServerIDEProject_ProjectPluginPart() {
  }
  @Override
  public void init(MPSProject project) {
    System.out.println("DONE");
  }
}
