package com.strumenta.mpsserver.modelhierarchy;

/*Generated by MPS */

import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.module.SModuleId;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.module.SModule;
import org.jetbrains.mps.openapi.module.SRepository;

public class MyModuleReference implements SModuleReference {

  private SModuleId id;
  private String name;

  public MyModuleReference(SModuleId id, String name) {
    this.id = id;
    this.name = name;
  }
  @NotNull
  @Override
  public SModuleId getModuleId() {
    return id;
  }
  @Nullable
  @Override
  public String getModuleName() {
    return name;
  }
  @Nullable
  @Override
  public SModule resolve(@NotNull SRepository repository) {
    throw new UnsupportedOperationException();
  }
}
