package com.strumenta.mpsserver.modelhierarchy;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModelReference;
import org.jetbrains.mps.openapi.model.SModelId;
import org.jetbrains.mps.openapi.model.SModelName;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.model.SModel;
import org.jetbrains.mps.openapi.module.SRepository;

public class MyModelReference implements SModelReference {

  private SModelId id;
  private String name;
  private SModelName sModelName;

  public MyModelReference(SModelId id, String name) {
    this.id = id;
    this.name = name;
    this.sModelName = new SModelName(name);
  }

  @NotNull
  @Override
  public SModelId getModelId() {
    return id;
  }
  @NotNull
  @Override
  public String getModelName() {
    return name;
  }
  @NotNull
  @Override
  public SModelName getName() {
    return sModelName;
  }
  @Nullable
  @Override
  public SModuleReference getModuleReference() {
    throw new UnsupportedOperationException();
  }
  @Override
  public SModel resolve(SRepository repository) {
    SModel res = repository.getModel(this.getModelId());
    return res;
  }
  @Override
  public String toString() {
    return "MyModelReference[" + sModelName + ", " + name + ", " + id + "]";
  }
}
